name: Deploy to Koyeb

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Koyeb CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
        export PATH=$PATH:/home/runner/.koyeb/bin

    - name: Login to Koyeb CLI
      run: koyeb login --api-key ${{ secrets.KOYEB_API_KEY }}

    - name: Deploy to Koyeb
      run: koyeb service redeploy brilliant-austina/sessions-bot
